### ISSUE TITLE
make sure to comment main parts of code

### ISSUE THREAD

**Issue by ad3429** [davidmikulis/prj-rev-bwfs-dasmoto#2]
https://github.com/davidmikulis/prj-rev-bwfs-dasmoto/blob/master/CraftStore/index.html#L2-L37

Make sure to comment the main parts of your HTML in future projects. This becomes increasingly important as your projects become larger and more complex. Here is a quick refresher on commenting in HTML:

<img width="197" alt="html_comment" src="https://user-images.githubusercontent.com/25671399/39784878-1357935a-52e8-11e8-88b6-89c4c6a98fde.png">

**Comment by davidmikulis** [comment]
(Refer to comment on #5 ) Working on feedback and will continue practicing to improve on future exercises and projects.
