### ISSUE TITLE
CSS is clean and succinct

### ISSUE THREAD

**Issue by ad3429** [davidmikulis/prj-rev-bwfs-dasmoto#3]
https://github.com/davidmikulis/prj-rev-bwfs-dasmoto/blob/master/CraftStore/resources/css/index.css#L1-L29

Your CSS is short and succinct -- good job! One area of improvement is to make sure to comment your main stylings so that when you come back to your code you remember exactly why you decided to style an element a particular way. Here is a quick refresher on commenting in CSS:

<img width="178" alt="css comment" src="https://user-images.githubusercontent.com/25671399/39784900-222582ca-52e8-11e8-8719-2fb5253c5fa2.png">

**Comment by davidmikulis** [comment]
(Refer to comment on #5 ) Working on feedback and will continue practicing to improve on future exercises and projects.
