### ISSUE TITLE
HTML nicely formatted/organized

### ISSUE THREAD

**Issue by ad3429** [davidmikulis/prj-rev-bwfs-dasmoto#4]
https://github.com/davidmikulis/prj-rev-bwfs-dasmoto/blob/master/CraftStore/index.html#L1-L37

Your HTML is for the most part very nicely organized/formatted. Make sure to keep it up!

**Comment by davidmikulis** [comment]
(Refer to comment on #5 ) Working on feedback and will continue practicing to improve on future exercises and projects.
